// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "FireflyAbilitySystemTypes.generated.h"

/** 个人技能系统的属性枚举，在项目设置中定义DisplayName */
UENUM(BlueprintType)
enum EFireflyAttributeType
{
	AttributeType_Default UMETA(DisplayName = "Default"),
	AttributeType01 UMETA(Hidden),
	AttributeType02 UMETA(Hidden),
	AttributeType03 UMETA(Hidden),
	AttributeType04 UMETA(Hidden),
	AttributeType05 UMETA(Hidden),
	AttributeType06 UMETA(Hidden),
	AttributeType07 UMETA(Hidden),
	AttributeType08 UMETA(Hidden),
	AttributeType09 UMETA(Hidden),
	AttributeType10 UMETA(Hidden),
	AttributeType11 UMETA(Hidden),
	AttributeType12 UMETA(Hidden),
	AttributeType13 UMETA(Hidden),
	AttributeType14 UMETA(Hidden),
	AttributeType15 UMETA(Hidden),
	AttributeType16 UMETA(Hidden),
	AttributeType17 UMETA(Hidden),
	AttributeType18 UMETA(Hidden),
	AttributeType19 UMETA(Hidden),
	AttributeType20 UMETA(Hidden),
	AttributeType21 UMETA(Hidden),
	AttributeType22 UMETA(Hidden),
	AttributeType23 UMETA(Hidden),
	AttributeType24 UMETA(Hidden),
	AttributeType25 UMETA(Hidden),
	AttributeType26 UMETA(Hidden),
	AttributeType27 UMETA(Hidden),
	AttributeType28 UMETA(Hidden),
	AttributeType29 UMETA(Hidden),
	AttributeType30 UMETA(Hidden),
	AttributeType31 UMETA(Hidden),
	AttributeType32 UMETA(Hidden),
	AttributeType33 UMETA(Hidden),
	AttributeType34 UMETA(Hidden),
	AttributeType35 UMETA(Hidden),
	AttributeType36 UMETA(Hidden),
	AttributeType37 UMETA(Hidden),
	AttributeType38 UMETA(Hidden),
	AttributeType39 UMETA(Hidden),
	AttributeType40 UMETA(Hidden),
	AttributeType41 UMETA(Hidden),
	AttributeType42 UMETA(Hidden),
	AttributeType43 UMETA(Hidden),
	AttributeType44 UMETA(Hidden),
	AttributeType45 UMETA(Hidden),
	AttributeType46 UMETA(Hidden),
	AttributeType47 UMETA(Hidden),
	AttributeType48 UMETA(Hidden),
	AttributeType49 UMETA(Hidden),
	AttributeType50 UMETA(Hidden),
	AttributeType51 UMETA(Hidden),
	AttributeType52 UMETA(Hidden),
	AttributeType53 UMETA(Hidden),
	AttributeType54 UMETA(Hidden),
	AttributeType55 UMETA(Hidden),
	AttributeType56 UMETA(Hidden),
	AttributeType57 UMETA(Hidden),
	AttributeType58 UMETA(Hidden),
	AttributeType59 UMETA(Hidden),
	AttributeType60 UMETA(Hidden),
	AttributeType61 UMETA(Hidden),
	AttributeType62 UMETA(Hidden),
	AttributeType_Max UMETA(Hidden)
};